### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by titu3e** [kennedy-ex/EmikoRobot#39]
cant add user into database

**Comment by kennedy-ex** [comment]
Really? see your logs if logs like

`[SQL: INSERT INTO users (user_id, username) VALUES (%(user_id)s, %(username)s)]
[parameters: {'user_id': 1895161193, 'username': 'myatthur'}]
(Background on this error at: https://sqlalche.me/e/14/f405) (Background on this error at: https://sqlalche.me/e/14/7s2a):</code> <b>442</b> #CRLWW`

mean your db is full.
