### ISSUE TITLE
Heroku link

### ISSUE THREAD

**Issue by lintobinoy007** [kennedy-ex/EmikoRobot#49]
Heroku link is not opening

**Comment by kennedy-ex** [comment]
You can fork it and change the github name on deploy link.

**Comment by lintobinoy007** [comment]
okk but it showing salesforce issue

**Comment by kennedy-ex** [comment]
read my quote, "fork and change deploy link".

**Comment by kennedy-ex** [comment]
U don't understand? ok i'll give a the sample.

Real Link: 
https://heroku.com/deploy?template=https://github.com/`kennedy-ex`/EmikoRobot

Fork Link: https://heroku.com/deploy?template=https://github.com/`<your_github>`/EmikoRobot (delete the <> and fill with your github).

**Comment by kennedy-ex** [comment]
> okk but it showing salesforce issue

U don't understand? ok i'll give a the sample.

Real Link:
https://heroku.com/deploy?template=https://github.com/kennedy-ex/EmikoRobot

Just change the "kennedy-ex" with your github username.

**Comment by lintobinoy007** [comment]
music player and anti spam is not working

**Comment by jamalnggau1** [comment]
> music player and anti spam is not working

Yes🥺

**Comment by lintobinoy007** [comment]
😔😢 will you do something
